# Generated by Django 5.2.10 on 2026-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="The unique URL identifier for this component. Changing this after the profile is public will break existing links.",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="dummys/images/"
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dummys",
            },
        ),
    ]
